application:
  name: Hotel_Management

server:
  port: 1998

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_management
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update #to create the table if not exists, [create, create-drop, update, validate, none]
    show-sql: true #to dispaly the sql query
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect #need to search